name       : libnotify
version    : 0.7.9
release    : 6
source     :
    - https://download.gnome.org/sources/libnotify/0.7/libnotify-0.7.9.tar.xz : 66c0517ed16df7af258e83208faaf5069727dfd66995c4bbc51c16954d674761
homepage   : http://www.gnome.org
component  : desktop.gnome.core
license    : GPL-2.0-or-later
emul32     : yes
summary    : Desktop notifications library
description: |
    The libnotify library is used to send desktop notifications to a notification daemon, as defined in the Desktop Notifications spec. These notifications can be used to inform the user about an event or display some form of information without getting in the user's way.
builddeps  :
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(gtk+-3.0)
    - docbook-xml
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
        build_man=false
    else
        build_gobject="enabled"
        build_man=true
    fi
    %meson_configure \
        -Ddocbook_docs="disabled" \
        -Dgtk_doc=false \
        -Dintrospection=$build_gobject \
        -Dman=$build_man
build      : |
    %ninja_build
install    : |
    %ninja_install
