name       : libnotify
version    : 0.7.7
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libnotify/0.7/libnotify-0.7.7.tar.xz : 9cb4ce315b2655860c524d46b56010874214ec27e854086c1a1d0260137efc04
homepage   : http://www.gnome.org
component  : desktop.gnome.core
license    : GPL-2.0
emul32     : yes
summary    : Desktop notifications library
description: |
    The libnotify library is used to send desktop notifications to a notification daemon, as defined in the Desktop Notifications spec. These notifications can be used to inform the user about an event or display some form of information without getting in the user's way.
builddeps  :
    - pkgconfig32(atk)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(pangocairo)
    - pkgconfig32(cairo)
    - pkgconfig32(gdk-pixbuf-2.0)
    - pkgconfig32(gtk+-3.0)
patterns   :
    - docs : [/usr/share/doc, /usr/share/gtk-doc]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
